version: '2'

services:
  bcoin:
    build:
      context: .
    container_name: bcoin_tn
    restart: unless-stopped
    ports:
      #-- Mainnet
      #- "8333:8333"
      #- "8332:8332" # RPC/HTTP
      #- "8334:8334" # Wallet
      #-- Testnet
      - "18333:18333"
      - "18332:18332" # RPC/HTTP
      - "18334:18334"
    environment:
      BCOIN_CONFIG: /data/bcoin.conf
      VIRTUAL_HOST: bcoin.yourdomain.org
      #VIRTUAL_PORT: 8332
      VIRTUAL_PORT: 18332 # Testnest
       BCOIN_VERSION: v2.2.0
    networks:
      - "bcoin"
      - "nginx-proxy"
    volumes:
      - ~/.bcoin:/data
      - ${PWD}/secrets/bcoin.conf:/data/bcoin.conf
      - ${PWD}/secrets/wallet.conf:/data/wallet.conf

networks:
  bcoin_tn:
    external:
      name: "bcoin"
